x<-read.csv2(file = "~/household_power_consumption/household_power_consumption.txt",dec = ".",na.strings = "?",colClasses = c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"))
library(dplyr)
febdates<-mutate(x,date=as.Date(x$Date,"%e/%m/%Y"))
febdates2<-filter(febdates,date=="2007-02-01")
febdates3<-filter(febdates,date=="2007-02-02")
febdates4<-rbind(febdates2,febdates3)
febdates5<-mutate(febdates4,datetime=paste(febdates4[[1]],febdates4[[2]]))
date2<-strptime(febdates5$datetime,"%e/%m/%Y %H:%M:%S")
par(mfrow=c(2,2),mar=c(4,4,2,1))
plot(date2,febdates5$Global_active_power,type = "l",xlab = "",ylab = "Global Active Power (kilowatts)")
plot(date2,febdates5$Voltage,type = "l",xlab = "datetime",ylab = "Voltage",lab=c(8,8,7))
plot(date2,febdates5$Sub_metering_1,type = "n",xlab = "",ylab = "Energy sub metering")
lines(date2,febdates5$Sub_metering_1,col="black")
lines(date2,febdates5$Sub_metering_2,col="red")
lines(date2,febdates5$Sub_metering_3,col="blue")
legend("topright",col=c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty = c(1,1,1),cex = 0.5,bty = "n")
plot(date2,febdates5$Global_reactive_power,type = "l",xlab = "datetime",ylab = "Global_reactive_power")
dev.copy(png,"plot4.png")
dev.off()

