x<-read.csv2(file = "~/household_power_consumption/household_power_consumption.txt",dec = ".",na.strings = "?",colClasses = c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"))
library(dplyr)
febdates<-mutate(x,date=as.Date(x$Date,"%e/%m/%Y"))
febdates2<-filter(febdates,date=="2007-02-01")
febdates3<-filter(febdates,date=="2007-02-02")
febdates4<-rbind(febdates2,febdates3)
hist(febdates4$Global_active_power,xlab="Global Active Power (kilowatts)",col="red",ylim = c(0,1200),main = "Global Active Power")
dev.copy(png,"plot1.png")
dev.off()
