x<-read.csv2(file = "~/household_power_consumption/household_power_consumption.txt",dec = ".",na.strings = "?",colClasses = c("character","character","numeric","numeric","numeric","numeric","numeric","numeric","numeric"))
library(dplyr)
febdates<-mutate(x,date=as.Date(x$Date,"%e/%m/%Y"))
febdates2<-filter(febdates,date=="2007-02-01")
febdates3<-filter(febdates,date=="2007-02-02")
febdates4<-rbind(febdates2,febdates3)
febdates5<-mutate(febdates4,datetime=paste(febdates4[[1]],febdates4[[2]]))
date2<-strptime(febdates5$datetime,"%e/%m/%Y %H:%M:%S")
plot(date2,febdates5$Global_active_power,type = "l",xlab = "",ylab = "Global Active Power (kilowatts)")
dev.copy(png,"plot2.png")
dev.off()